"""PostgreSQL adapter for the existing SQLite queries; amounts remain integer cents."""
import os
import re
from contextlib import contextmanager
from contextvars import ContextVar

CURRENT_CONNECTION = ContextVar('database_transaction', default=None)
IDENTITIES = {'operations', 'savings_goals', 'goal_movements', 'trips'}
TABLE_COLUMNS = {
    'user_settings': ('user_id', 'key', 'value'),
    'user_overrides': ('user_id', 'needle', 'category'),
    'user_budgets': ('user_id', 'category', 'currency', 'amount_cents'),
}
CONFLICT_KEYS = {'user_settings': 2, 'user_overrides': 2, 'user_budgets': 3}

class Row(dict):
    def __getitem__(self, key):
        return tuple(self.values())[key] if isinstance(key, int) else super().__getitem__(key)

def row_factory(cursor):
    names = [column.name for column in cursor.description] if cursor.description else []
    return lambda values: Row(zip(names, values))

def translate(sql):
    ignore = bool(re.match(r'INSERT OR IGNORE', sql, re.I))
    replace = re.match(r'INSERT OR REPLACE INTO (\w+)', sql, re.I)
    sql = re.sub(r'INSERT OR (?:IGNORE|REPLACE)', 'INSERT', sql, flags=re.I)
    if replace:
        table = replace.group(1)
        columns = TABLE_COLUMNS[table]
        keys = columns[:CONFLICT_KEYS[table]]
        sql += ' ON CONFLICT (' + ','.join(keys) + ') DO UPDATE SET ' + ','.join(f'{c}=EXCLUDED.{c}' for c in columns if c not in keys)
    elif ignore:
        sql += ' ON CONFLICT DO NOTHING'
    insert = re.match(r'INSERT INTO (\w+)', sql, re.I)
    returning = bool(insert and insert.group(1) in IDENTITIES)
    if returning:
        sql += ' RETURNING id'
    # Escape psycopg's percent markers; replace placeholders outside SQL literals.
    sql = sql.replace('%', '%%')
    pieces = re.split(r"('(?:''|[^'])*')", sql)
    sql = ''.join(piece if i % 2 else piece.replace('?', '%s') for i, piece in enumerate(pieces))
    return sql, returning

class Cursor:
    def __init__(self, cursor, returning):
        self._cursor = cursor
        self.lastrowid = None
        self.rowcount = cursor.rowcount
        if returning:
            row = cursor.fetchone()
            self.lastrowid = row['id'] if row else None
    def fetchone(self): return self._cursor.fetchone()
    def fetchall(self): return self._cursor.fetchall()
    def __iter__(self): return iter(self._cursor)

class Connection:
    def __init__(self, raw): self.raw = raw
    def execute(self, sql, params=()):
        query, returning = translate(sql)
        return Cursor(self.raw.execute(query, params), returning)

@contextmanager
def transaction():
    import psycopg
    with psycopg.connect(os.environ['DATABASE_URL'], row_factory=row_factory, connect_timeout=15) as raw:
        connection = Connection(raw)
        token = CURRENT_CONNECTION.set(connection)
        try:
            yield connection
        finally:
            CURRENT_CONNECTION.reset(token)

@contextmanager
def connection():
    existing = CURRENT_CONNECTION.get()
    if existing is not None:
        yield existing
    else:
        with transaction() as current: yield current

SCHEMA = '''
CREATE TABLE IF NOT EXISTS operations (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL,
 source TEXT NOT NULL, external_id TEXT, account_id TEXT, day TEXT NOT NULL,
 amount_cents BIGINT NOT NULL, currency TEXT NOT NULL, description TEXT NOT NULL,
 category TEXT NOT NULL, income_category TEXT, trip_id BIGINT, trip_category TEXT,
 UNIQUE(user_id,source,account_id,external_id));
CREATE TABLE IF NOT EXISTS user_settings(user_id BIGINT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,PRIMARY KEY(user_id,key));
CREATE TABLE IF NOT EXISTS user_overrides(user_id BIGINT NOT NULL,needle TEXT NOT NULL,category TEXT NOT NULL,PRIMARY KEY(user_id,needle));
CREATE TABLE IF NOT EXISTS user_budgets(user_id BIGINT NOT NULL,category TEXT NOT NULL,currency TEXT NOT NULL,amount_cents BIGINT NOT NULL,PRIMARY KEY(user_id,category,currency));
CREATE TABLE IF NOT EXISTS savings_goals(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,name TEXT NOT NULL,currency TEXT NOT NULL,target_cents BIGINT NOT NULL CHECK(target_cents>0),created_day TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS goal_movements(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,goal_id BIGINT NOT NULL REFERENCES savings_goals(id),amount_cents BIGINT NOT NULL CHECK(amount_cents!=0),day TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS trips(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,user_id BIGINT NOT NULL,name TEXT NOT NULL,currency TEXT NOT NULL,budget_cents BIGINT,active INTEGER NOT NULL DEFAULT 0,created_day TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS operations_user_day ON operations(user_id,day);
CREATE INDEX IF NOT EXISTS operations_trip ON operations(user_id,trip_id);
CREATE INDEX IF NOT EXISTS goal_movements_owner ON goal_movements(user_id,goal_id);
CREATE INDEX IF NOT EXISTS trips_owner ON trips(user_id,id);
CREATE TABLE IF NOT EXISTS bot_user_state(user_id BIGINT PRIMARY KEY,state TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS processed_updates(update_id BIGINT PRIMARY KEY,processed_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS migration_log(name TEXT PRIMARY KEY,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
'''

def initialize():
    with transaction() as c:
        for statement in SCHEMA.split(';'):
            if statement.strip(): c.raw.execute(statement)
